export const TEAMS = [
  { name: "Allemagne", flag: "🇩🇪" }, { name: "Angleterre", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { name: "Autriche", flag: "🇦🇹" }, { name: "Belgique", flag: "🇧🇪" },
  { name: "Bosnie-Herzégovine", flag: "🇧🇦" }, { name: "Croatie", flag: "🇭🇷" },
  { name: "Espagne", flag: "🇪🇸" }, { name: "France", flag: "🇫🇷" },
  { name: "Norvège", flag: "🇳🇴" }, { name: "Pays-Bas", flag: "🇳🇱" },
  { name: "Portugal", flag: "🇵🇹" }, { name: "Suède", flag: "🇸🇪" },
  { name: "Suisse", flag: "🇨🇭" }, { name: "Tchéquie", flag: "🇨🇿" },
  { name: "Turquie", flag: "🇹🇷" }, { name: "Écosse", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { name: "Argentine", flag: "🇦🇷" }, { name: "Brésil", flag: "🇧🇷" },
  { name: "Colombie", flag: "🇨🇴" }, { name: "Équateur", flag: "🇪🇨" },
  { name: "Paraguay", flag: "🇵🇾" }, { name: "Uruguay", flag: "🇺🇾" },
  { name: "Afrique du Sud", flag: "🇿🇦" }, { name: "Algérie", flag: "🇩🇿" },
  { name: "Cap-Vert", flag: "🇨🇻" }, { name: "Côte d'Ivoire", flag: "🇨🇮" },
  { name: "Égypte", flag: "🇪🇬" }, { name: "Ghana", flag: "🇬🇭" },
  { name: "Maroc", flag: "🇲🇦" }, { name: "RD Congo", flag: "🇨🇩" },
  { name: "Sénégal", flag: "🇸🇳" }, { name: "Tunisie", flag: "🇹🇳" },
  { name: "Arabie Saoudite", flag: "🇸🇦" }, { name: "Australie", flag: "🇦🇺" },
  { name: "Corée du Sud", flag: "🇰🇷" }, { name: "Iran", flag: "🇮🇷" },
  { name: "Irak", flag: "🇮🇶" }, { name: "Japon", flag: "🇯🇵" },
  { name: "Jordanie", flag: "🇯🇴" }, { name: "Qatar", flag: "🇶🇦" },
  { name: "Ouzbékistan", flag: "🇺🇿" },
  { name: "Canada", flag: "🇨🇦" }, { name: "Curaçao", flag: "🇨🇼" },
  { name: "États-Unis", flag: "🇺🇸" }, { name: "Haïti", flag: "🇭🇹" },
  { name: "Mexique", flag: "🇲🇽" }, { name: "Panama", flag: "🇵🇦" },
  { name: "Nouvelle-Zélande", flag: "🇳🇿" },
];
